/** @type {import('tailwindcss').Config} */
module.exports = {
  darkMode: 'class',
  content: [
    './app/**/*.{js,ts,jsx,tsx,mdx}',
    './components/**/*.{js,ts,jsx,tsx,mdx}',
  ],
  theme: {
    extend: {
      colors: {
        brand: {
          50: 'var(--fleet-brand-50)',
          100: 'var(--fleet-brand-100)',
          500: 'var(--fleet-brand-500)',
          600: 'var(--fleet-brand-600)',
          700: 'var(--fleet-brand-700)',
          900: 'var(--fleet-brand-900)',
        },
        gray: {
          25: 'var(--fleet-gray-25)',
          50: 'var(--fleet-gray-50)',
          100: 'var(--fleet-gray-100)',
          200: 'var(--fleet-gray-200)',
          300: 'var(--fleet-gray-300)',
          400: 'var(--fleet-gray-400)',
          500: 'var(--fleet-gray-500)',
          600: 'var(--fleet-gray-600)',
          700: 'var(--fleet-gray-700)',
          800: 'var(--fleet-gray-800)',
          900: 'var(--fleet-gray-900)',
          950: 'var(--fleet-gray-950)',
        },
        status: {
          success: 'var(--status-success)',
          'success-bg': 'var(--status-success-bg)',
          'success-text': 'var(--status-success-text)',
          warning: 'var(--status-warning)',
          'warning-bg': 'var(--status-warning-bg)',
          'warning-text': 'var(--status-warning-text)',
          error: 'var(--status-error)',
          'error-bg': 'var(--status-error-bg)',
          'error-text': 'var(--status-error-text)',
          info: 'var(--status-info)',
          'info-bg': 'var(--status-info-bg)',
          'info-text': 'var(--status-info-text)',
        },
        surface: {
          base: 'var(--fleet-surface-base)',
          raised: 'var(--fleet-surface-raised)',
          muted: 'var(--fleet-surface-muted)',
          sunken: 'var(--fleet-surface-sunken)',
        },
        border: {
          DEFAULT: 'var(--fleet-border)',
          strong: 'var(--fleet-border-strong)',
          focus: 'var(--fleet-border-focus)',
        },
        // shadcn compat
        background: 'hsl(var(--background))',
        foreground: 'hsl(var(--foreground))',
        card: { DEFAULT: 'hsl(var(--card))', foreground: 'hsl(var(--card-foreground))' },
        popover: { DEFAULT: 'hsl(var(--popover))', foreground: 'hsl(var(--popover-foreground))' },
        primary: { DEFAULT: 'hsl(var(--primary))', foreground: 'hsl(var(--primary-foreground))' },
        secondary: { DEFAULT: 'hsl(var(--secondary))', foreground: 'hsl(var(--secondary-foreground))' },
        muted: { DEFAULT: 'hsl(var(--muted))', foreground: 'hsl(var(--muted-foreground))' },
        accent: { DEFAULT: 'hsl(var(--accent))', foreground: 'hsl(var(--accent-foreground))' },
        destructive: { DEFAULT: 'hsl(var(--destructive))', foreground: 'hsl(var(--destructive-foreground))' },
        input: 'hsl(var(--input))',
        ring: 'hsl(var(--ring))',
        chart: {
          1: 'hsl(var(--chart-1))',
          2: 'hsl(var(--chart-2))',
          3: 'hsl(var(--chart-3))',
          4: 'hsl(var(--chart-4))',
          5: 'hsl(var(--chart-5))',
        },
      },
      fontFamily: {
        sans: ['Inter', 'ui-sans-serif', '-apple-system', 'BlinkMacSystemFont', 'Segoe UI', 'Roboto', 'sans-serif'],
        mono: ['JetBrains Mono', 'SF Mono', 'Fira Code', 'monospace'],
      },
      fontSize: {
        '2xs': ['11px', { lineHeight: '16px' }],
        xs: ['12px', { lineHeight: '18px' }],
        sm: ['14px', { lineHeight: '20px' }],
        base: ['14px', { lineHeight: '20px' }],
        md: ['16px', { lineHeight: '24px' }],
        lg: ['18px', { lineHeight: '28px' }],
        xl: ['20px', { lineHeight: '28px' }],
        '2xl': ['24px', { lineHeight: '32px' }],
        '3xl': ['30px', { lineHeight: '38px' }],
        '4xl': ['36px', { lineHeight: '44px' }],
      },
      spacing: {
        '4.5': '18px',
        '13': '52px',
        '15': '60px',
        '18': '72px',
        '22': '88px',
      },
      borderRadius: {
        xs: 'var(--fleet-radius-xs)',
        sm: 'var(--fleet-radius-sm)',
        md: 'var(--fleet-radius-md)',
        lg: 'var(--fleet-radius-lg)',
        xl: 'var(--fleet-radius-xl)',
        '2xl': 'var(--fleet-radius-2xl)',
        pill: 'var(--fleet-radius-pill)',
      },
      boxShadow: {
        xs: 'var(--fleet-shadow-xs)',
        sm: 'var(--fleet-shadow-sm)',
        md: 'var(--fleet-shadow-md)',
        lg: 'var(--fleet-shadow-lg)',
        xl: 'var(--fleet-shadow-xl)',
      },
      transitionDuration: {
        fast: 'var(--fleet-duration-fast)',
        normal: 'var(--fleet-duration-normal)',
        slow: 'var(--fleet-duration-slow)',
      },
      transitionTimingFunction: {
        fleet: 'var(--fleet-ease)',
      },
      keyframes: {
        'fade-in': {
          from: { opacity: '0', transform: 'translateY(8px)' },
          to: { opacity: '1', transform: 'none' },
        },
        'slide-in-right': {
          from: { transform: 'translateX(100%)' },
          to: { transform: 'translateX(0)' },
        },
        'scale-in': {
          from: { opacity: '0', transform: 'scale(0.95)' },
          to: { opacity: '1', transform: 'scale(1)' },
        },
      },
      animation: {
        'fade-in': 'fade-in 0.3s cubic-bezier(0.25, 0.1, 0.25, 1) both',
        'slide-in-right': 'slide-in-right 0.3s cubic-bezier(0.25, 0.1, 0.25, 1) both',
        'scale-in': 'scale-in 0.2s cubic-bezier(0.25, 0.1, 0.25, 1) both',
      },
    },
  },
  plugins: [require('tailwindcss-animate')],
};
