/** @type {import('tailwindcss').Config} */
module.exports = {
  content: [
    './app/**/*.{js,ts,jsx,tsx,mdx}',
    './components/**/*.{js,ts,jsx,tsx,mdx}',
  ],
  theme: {
    extend: {
      colors: {
        background: 'hsl(var(--background))',
        foreground: 'hsl(var(--foreground))',
        card: { DEFAULT: 'hsl(var(--card))', foreground: 'hsl(var(--card-foreground))' },
        primary: { DEFAULT: 'hsl(var(--primary))', foreground: 'hsl(var(--primary-foreground))' },
        secondary: { DEFAULT: 'hsl(var(--secondary))', foreground: 'hsl(var(--secondary-foreground))' },
        muted: { DEFAULT: 'hsl(var(--muted))', foreground: 'hsl(var(--muted-foreground))' },
        accent: { DEFAULT: 'hsl(var(--accent))', foreground: 'hsl(var(--accent-foreground))' },
        border: 'hsl(var(--border))',
        input: 'hsl(var(--input))',
        ring: 'hsl(var(--ring))',
        fleet: {
          'text-primary': 'var(--fleet-text-primary)',
          'text-secondary': 'var(--fleet-text-secondary)',
          'text-tertiary': 'var(--fleet-text-tertiary)',
          'surface-base': 'var(--fleet-surface-base)',
          'surface-muted': 'var(--fleet-surface-muted)',
          'surface-raised': 'var(--fleet-surface-raised)',
          'surface-strong': 'var(--fleet-surface-strong)',
        },
        night: {
          base: 'var(--fleet-night-base)',
          card: 'var(--fleet-night-card)',
          raised: 'var(--fleet-night-raised)',
          line: 'var(--fleet-night-line)',
          muted: 'var(--fleet-night-muted)',
        },
      },
      fontFamily: {
        sans: ['var(--fleet-font-primary)'],
      },
      fontSize: {
        xs: 'var(--fleet-font-size-xs)',
        sm: 'var(--fleet-font-size-sm)',
        md: 'var(--fleet-font-size-md)',
        lg: 'var(--fleet-font-size-lg)',
        xl: 'var(--fleet-font-size-xl)',
        '2xl': 'var(--fleet-font-size-2xl)',
        '3xl': 'var(--fleet-font-size-3xl)',
        '4xl': 'var(--fleet-font-size-4xl)',
      },
      spacing: {
        1: 'var(--fleet-space-1)',
        2: 'var(--fleet-space-2)',
        3: 'var(--fleet-space-3)',
        4: 'var(--fleet-space-4)',
        5: 'var(--fleet-space-5)',
        6: 'var(--fleet-space-6)',
        7: 'var(--fleet-space-7)',
        8: 'var(--fleet-space-8)',
      },
      borderRadius: {
        xs: 'var(--fleet-radius-xs)',
        sm: 'var(--fleet-radius-sm)',
        md: 'var(--fleet-radius-md)',
        lg: 'var(--fleet-radius-lg)',
        pill: 'var(--fleet-radius-pill)',
      },
      transitionDuration: {
        instant: 'var(--fleet-motion-instant)',
        fast: 'var(--fleet-motion-fast)',
        slow: 'var(--fleet-motion-slow)',
      },
    },
  },
  plugins: [require('tailwindcss-animate')],
};
