/**
 * RFC 7807 error codes for Fleet OS.
 * Add new codes here — never use inline strings.
 */
export const ERROR_CODES = {
  SESSION_OVERLAP: 'SESSION_OVERLAP',
  EDIT_WINDOW_CLOSED: 'EDIT_WINDOW_CLOSED',
  EVIDENCE_REQUIRED: 'EVIDENCE_REQUIRED',
  OCR_MISMATCH_REVIEW: 'OCR_MISMATCH_REVIEW',
  EXPENSE_DUPLICATE_SUSPECT: 'EXPENSE_DUPLICATE_SUSPECT',
  FX_RATE_REQUIRED: 'FX_RATE_REQUIRED',
  ENTITLEMENT_LIMIT: 'ENTITLEMENT_LIMIT',
  PAYMENT_HOLD: 'PAYMENT_HOLD',
} as const;

export type ErrorCode = (typeof ERROR_CODES)[keyof typeof ERROR_CODES];
